import { Booking, Provider, ProviderThread } from '../types';

const now = Date.now();
const buildSlot = (startHours: number, durationHours: number) => ({
  start: new Date(now + startHours * 3600000).toISOString(),
  end: new Date(now + (startHours + durationHours) * 3600000).toISOString(),
});

export const mockProviders: Provider[] = [
  {
    id: 'p-1',
    name: 'Farhan Saeed',
    serviceCategory: 'Plumbing',
    rating: 4.9,
    jobsCompleted: 142,
    hourlyRate: 2800,
    isAvailable: true,
    location: { latitude: 33.6844, longitude: 73.0479 },
    distance: 1.2,
    phone: '+923001234567',
    responseTimeMins: 5,
    preferredContact: 'chat',
    reliabilityScore: 0.92,
    cancellationRate: 0.04,
    onTimeScore: 0.9,
    disputeIndex: 0.06,
    specializationLevel: 'COMPLEX',
    availabilitySlots: [buildSlot(2, 3), buildSlot(8, 4)],
  },
  {
    id: 'p-2',
    name: 'Ahsan Malik',
    serviceCategory: 'Electrical',
    rating: 4.8,
    jobsCompleted: 98,
    hourlyRate: 3200,
    isAvailable: true,
    location: { latitude: 33.6950, longitude: 73.1045 },
    distance: 2.4,
    phone: '+923009876543',
    responseTimeMins: 15,
    preferredContact: 'call',
    reliabilityScore: 0.88,
    cancellationRate: 0.08,
    onTimeScore: 0.86,
    disputeIndex: 0.09,
    specializationLevel: 'INTERMEDIATE',
    availabilitySlots: [buildSlot(3, 2), buildSlot(10, 3)],
  },
  {
    id: 'p-3',
    name: 'Hassan Khan',
    serviceCategory: 'HVAC',
    rating: 4.7,
    jobsCompleted: 215,
    hourlyRate: 3800,
    isAvailable: false,
    location: { latitude: 33.6700, longitude: 73.1650 },
    distance: 3.1,
    responseTimeMins: 30,
    preferredContact: 'whatsapp',
    reliabilityScore: 0.7,
    cancellationRate: 0.22,
    onTimeScore: 0.72,
    disputeIndex: 0.18,
    specializationLevel: 'COMPLEX',
    availabilitySlots: [buildSlot(6, 2)],
  },
  {
    id: 'p-4',
    name: 'Zainab Mirza',
    serviceCategory: 'Cleaning',
    rating: 5.0,
    jobsCompleted: 304,
    hourlyRate: 1500,
    isAvailable: true,
    location: { latitude: 33.5850, longitude: 73.1950 },
    distance: 0.8,
    phone: '+923201234567',
    responseTimeMins: 10,
    preferredContact: 'chat',
    reliabilityScore: 0.95,
    cancellationRate: 0.03,
    onTimeScore: 0.93,
    disputeIndex: 0.04,
    specializationLevel: 'BASIC',
    availabilitySlots: [buildSlot(1, 2), buildSlot(7, 3)],
  },
  {
    id: 'p-5',
    name: 'Muhammad Tahir',
    serviceCategory: 'Handyman',
    rating: 4.6,
    jobsCompleted: 67,
    hourlyRate: 2000,
    isAvailable: true,
    location: { latitude: 33.5680, longitude: 73.1650 },
    distance: 4.5,
    phone: '+923005551234',
    responseTimeMins: 20,
    preferredContact: 'call',
    reliabilityScore: 0.8,
    cancellationRate: 0.18,
    onTimeScore: 0.78,
    disputeIndex: 0.2,
    specializationLevel: 'INTERMEDIATE',
    availabilitySlots: [buildSlot(4, 2), buildSlot(12, 2)],
  },
  {
    id: 'p-6',
    name: 'Ali Raza',
    serviceCategory: 'Appliance Repair',
    rating: 4.9,
    jobsCompleted: 320,
    hourlyRate: 2500,
    isAvailable: true,
    location: { latitude: 33.6844, longitude: 73.0479 },
    distance: 1.8,
    phone: '+923001112233',
    responseTimeMins: 10,
    preferredContact: 'chat',
    reliabilityScore: 0.9,
    cancellationRate: 0.07,
    onTimeScore: 0.88,
    disputeIndex: 0.08,
    specializationLevel: 'INTERMEDIATE',
    availabilitySlots: [buildSlot(2, 2), buildSlot(9, 3)],
  },
  {
    id: 'p-7',
    name: 'Omar Farooq',
    serviceCategory: 'Auto Mechanic',
    rating: 4.8,
    jobsCompleted: 156,
    hourlyRate: 3000,
    isAvailable: true,
    location: { latitude: 33.6950, longitude: 73.1045 },
    distance: 2.1,
    responseTimeMins: 45,
    preferredContact: 'call',
    reliabilityScore: 0.84,
    cancellationRate: 0.12,
    onTimeScore: 0.82,
    disputeIndex: 0.11,
    specializationLevel: 'COMPLEX',
    availabilitySlots: [buildSlot(5, 3), buildSlot(11, 2)],
  },
  {
    id: 'p-8',
    name: 'Fatima Noor',
    serviceCategory: 'Tutoring',
    rating: 5.0,
    jobsCompleted: 89,
    hourlyRate: 1200,
    isAvailable: true,
    location: { latitude: 33.5850, longitude: 73.1950 },
    distance: 0.5,
    phone: '+923204445566',
    responseTimeMins: 5,
    preferredContact: 'chat',
    reliabilityScore: 0.97,
    cancellationRate: 0.02,
    onTimeScore: 0.95,
    disputeIndex: 0.03,
    specializationLevel: 'BASIC',
    availabilitySlots: [buildSlot(1, 2), buildSlot(6, 2)],
  },
  {
    id: 'p-9',
    name: 'Ayesha Khan',
    serviceCategory: 'Beautician',
    rating: 4.9,
    jobsCompleted: 211,
    hourlyRate: 2300,
    isAvailable: true,
    location: { latitude: 33.6700, longitude: 73.1650 },
    distance: 1.1,
    phone: '+923207778899',
    responseTimeMins: 15,
    preferredContact: 'whatsapp',
    reliabilityScore: 0.91,
    cancellationRate: 0.06,
    onTimeScore: 0.89,
    disputeIndex: 0.07,
    specializationLevel: 'INTERMEDIATE',
    availabilitySlots: [buildSlot(3, 2), buildSlot(9, 2)],
  },
  {
    id: 'p-10',
    name: 'Bilal Ahmed',
    serviceCategory: 'AC Technician',
    rating: 4.8,
    jobsCompleted: 178,
    hourlyRate: 3500,
    isAvailable: true,
    location: { latitude: 33.5680, longitude: 73.1650 },
    distance: 1.9,
    phone: '+923009990011',
    responseTimeMins: 20,
    preferredContact: 'call',
    reliabilityScore: 0.86,
    cancellationRate: 0.1,
    onTimeScore: 0.84,
    disputeIndex: 0.12,
    specializationLevel: 'COMPLEX',
    availabilitySlots: [buildSlot(4, 3), buildSlot(10, 3)],
  }
];

export const mockProviderThreads: Record<string, ProviderThread> = {
  'p-1': {
    providerId: 'p-1',
    messages: [
      {
        id: 'msg-seed-1',
        providerId: 'p-1',
        role: 'provider',
        text: 'Assalam-o-Alaikum! Mein nay aap ka profile dekha hai. Agar plumbing ki zarorat ho to mujhe contact karain!',
        createdAt: new Date(Date.now() - 3600000).toISOString(),
      },
      {
        id: 'msg-seed-1b',
        providerId: 'p-1',
        role: 'user',
        text: 'Pipe line is not working, paani bahar nahin aa raha.',
        createdAt: new Date(Date.now() - 3500000).toISOString(),
      },
      {
        id: 'msg-seed-1c',
        providerId: 'p-1',
        role: 'provider',
        text: 'Ji mam, ap mujhe apni location bhej dijyega, taake mein check karun.',
        createdAt: new Date(Date.now() - 3490000).toISOString(),
      },
      {
        id: 'msg-seed-1d',
        providerId: 'p-1',
        role: 'user',
        text: 'Main ne location bhej di: G-11/3, Islamabad. Kab dekh sakte ho? Ich aap mujhe call karoge pehle?',
        createdAt: new Date(Date.now() - 3400000).toISOString(),
      },
      {
        id: 'msg-seed-1e',
        providerId: 'p-1',
        role: 'provider',
        text: 'Theek hai — mein aapko call karunga jab mein shop ke paas aa raha honga, phir aap se aagay ki details discuss karunga.',
        createdAt: new Date(Date.now() - 3395000).toISOString(),
      },
    ],
  },
  'p-4': {
    providerId: 'p-4',
    messages: [
      {
        id: 'msg-seed-2',
        providerId: 'p-4',
        role: 'user',
        text: 'Assalam! Kya aap ghar ki gehri safai ke liye mashinized cleaning karte ho?',
        createdAt: new Date(Date.now() - 7200000).toISOString(),
      },
      {
        id: 'msg-seed-3',
        providerId: 'p-4',
        role: 'provider',
        text: 'Bilkul! Mery pas specialized machine hai. Ek average room ke liye 2 ghante lagty hain.',
        createdAt: new Date(Date.now() - 7000000).toISOString(),
      },
    ],
  },
};

export const mockBookings: Booking[] = [
  {
    id: 'b-101',
    providerId: 'p-1',
    userId: 'u-1',
    status: 'in_progress',
    scheduledTime: new Date().toISOString(),
    estimatedCost: 5600,
    serviceDetails: 'Main bathroom mein burst pipe fix karna.',
    location: {
      latitude: 33.6844,
      longitude: 73.0479,
      address: 'G-11/3, Islamabad',
    },
  },
  {
    id: 'b-102',
    providerId: 'p-4',
    userId: 'u-1',
    status: 'pending',
    scheduledTime: new Date(Date.now() + 86400000).toISOString(), // Tomorrow
    estimatedCost: 3000,
    serviceDetails: '2 bedroom apartment ki gehri safai.',
    location: {
      latitude: 33.5850,
      longitude: 73.1950,
      address: 'Saddar, Rawalpindi',
    },
  },
];
